/**
 * Alabobai Executive Department Templates
 * OKRs, Board Decks, Strategic Planning Documents
 */

export const EXECUTIVE_TEMPLATES = {
  // ============================================================================
  // OKR (OBJECTIVES AND KEY RESULTS)
  // ============================================================================
  okr: {
    name: 'OKR Framework',
    description: 'Quarterly objectives and key results planning document',
    fields: ['companyName', 'quarter', 'year', 'objectives'],
    generate: (data: {
      companyName: string;
      quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4';
      year: number;
      teamName?: string;
      objectives: Array<{
        objective: string;
        owner: string;
        keyResults: Array<{
          result: string;
          metric: string;
          target: string;
          current?: string;
          confidence?: number;
        }>;
      }>;
      notes?: string;
    }) => `
================================================================================
${data.companyName.toUpperCase()}
${data.quarter} ${data.year} OKR FRAMEWORK
${data.teamName ? `Team: ${data.teamName}` : 'Company-Wide Objectives'}
================================================================================

Generated by Alabobai Executive Department
Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

================================================================================
OVERVIEW
================================================================================

This document outlines the Objectives and Key Results (OKRs) for ${data.quarter} ${data.year}.
OKRs help align our efforts, create focus, and measure progress toward our goals.

Grading Scale:
  0.0 - 0.3  = We failed to make real progress
  0.4 - 0.6  = We made progress but fell short
  0.7 - 1.0  = We delivered (0.7 is considered success)

================================================================================
OBJECTIVES AND KEY RESULTS
================================================================================

${data.objectives.map((obj, index) => `
OBJECTIVE ${index + 1}: ${obj.objective}
Owner: ${obj.owner}
--------------------------------------------------------------------------------

${obj.keyResults.map((kr, krIndex) => `
  KR ${index + 1}.${krIndex + 1}: ${kr.result}

    Metric:      ${kr.metric}
    Target:      ${kr.target}
    ${kr.current ? `Current:     ${kr.current}` : ''}
    ${kr.confidence !== undefined ? `Confidence:  ${(kr.confidence * 100).toFixed(0)}%` : ''}
    Status:      [ ] Not Started  [ ] In Progress  [ ] At Risk  [ ] On Track  [ ] Complete
`).join('\n')}

--------------------------------------------------------------------------------
`).join('\n')}

================================================================================
QUARTERLY MILESTONES
================================================================================

Week 1-4:   [ ] OKRs finalized and communicated
            [ ] Initial planning and resource allocation
            [ ] First check-in completed

Week 5-8:   [ ] Mid-quarter review conducted
            [ ] Course corrections identified
            [ ] Resources reallocated if needed

Week 9-12:  [ ] Final push on key results
            [ ] End-of-quarter grading
            [ ] Retrospective and learnings documented

================================================================================
TRACKING & REVIEW
================================================================================

Weekly Check-ins:
- Every Monday: Team leads update KR progress
- Traffic light status: Green / Yellow / Red

Monthly Reviews:
- End of each month: Full OKR review meeting
- Discuss blockers and dependencies
- Celebrate wins and learn from misses

Quarterly Retrospective:
- Grade all KRs on 0.0-1.0 scale
- Document learnings
- Input for next quarter's OKRs

================================================================================
DEPENDENCIES & RISKS
================================================================================

Key Dependencies:
1. _______________________________________________
2. _______________________________________________
3. _______________________________________________

Identified Risks:
1. _______________________________________________
   Mitigation: ___________________________________

2. _______________________________________________
   Mitigation: ___________________________________

3. _______________________________________________
   Mitigation: ___________________________________

${data.notes ? `
================================================================================
ADDITIONAL NOTES
================================================================================

${data.notes}
` : ''}

================================================================================
SIGNATURES
================================================================================

Prepared By:     _________________________  Date: ____________

Approved By:     _________________________  Date: ____________
                 (Executive Sponsor)

Team Lead:       _________________________  Date: ____________

================================================================================
                    Generated by Alabobai Executive Department
================================================================================
`
  },

  // ============================================================================
  // BOARD DECK / INVESTOR UPDATE
  // ============================================================================
  boardDeck: {
    name: 'Board Deck / Investor Update',
    description: 'Quarterly board meeting presentation deck outline',
    fields: ['companyName', 'quarter', 'year', 'metrics', 'highlights', 'financials'],
    generate: (data: {
      companyName: string;
      quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4';
      year: number;
      meetingDate: string;
      metrics: {
        arr?: number;
        mrr?: number;
        customers?: number;
        growth?: number;
        churn?: number;
        nps?: number;
        runway?: number;
      };
      highlights: string[];
      challenges: string[];
      financials: {
        revenue: number;
        expenses: number;
        burn: number;
        cash: number;
      };
      asks?: string[];
      nextQuarterGoals?: string[];
    }) => `
================================================================================
${data.companyName.toUpperCase()}
BOARD MEETING | ${data.quarter} ${data.year}
================================================================================

Meeting Date: ${data.meetingDate}
Prepared by: Executive Team

================================================================================
                              EXECUTIVE SUMMARY
================================================================================

This document provides an overview of ${data.companyName}'s performance for
${data.quarter} ${data.year}, including key metrics, highlights, challenges,
and our outlook for the coming quarter.

================================================================================
                              KEY METRICS SNAPSHOT
================================================================================

REVENUE & GROWTH
--------------------------------------------------------------------------------
${data.metrics.arr ? `Annual Recurring Revenue (ARR):     $${data.metrics.arr.toLocaleString()}` : ''}
${data.metrics.mrr ? `Monthly Recurring Revenue (MRR):    $${data.metrics.mrr.toLocaleString()}` : ''}
${data.metrics.growth !== undefined ? `Quarter-over-Quarter Growth:       ${data.metrics.growth > 0 ? '+' : ''}${data.metrics.growth}%` : ''}

CUSTOMERS
--------------------------------------------------------------------------------
${data.metrics.customers ? `Total Customers:                    ${data.metrics.customers.toLocaleString()}` : ''}
${data.metrics.churn !== undefined ? `Monthly Churn Rate:                 ${data.metrics.churn}%` : ''}
${data.metrics.nps !== undefined ? `Net Promoter Score (NPS):           ${data.metrics.nps}` : ''}

FINANCIAL HEALTH
--------------------------------------------------------------------------------
${data.metrics.runway !== undefined ? `Runway (months):                    ${data.metrics.runway}` : ''}
Cash Position:                      $${data.financials.cash.toLocaleString()}
Monthly Burn Rate:                  $${data.financials.burn.toLocaleString()}

================================================================================
                              FINANCIAL OVERVIEW
================================================================================

${data.quarter} ${data.year} FINANCIALS
--------------------------------------------------------------------------------

                                    Actual          % of Revenue
--------------------------------------------------------------------------------
Revenue                             $${data.financials.revenue.toLocaleString().padStart(12)}      100.0%
Operating Expenses                  $${data.financials.expenses.toLocaleString().padStart(12)}      ${((data.financials.expenses / data.financials.revenue) * 100).toFixed(1)}%
--------------------------------------------------------------------------------
Net Income (Loss)                   $${(data.financials.revenue - data.financials.expenses).toLocaleString().padStart(12)}      ${(((data.financials.revenue - data.financials.expenses) / data.financials.revenue) * 100).toFixed(1)}%

Cash & Runway:
  Starting Cash:         [To be filled]
  Ending Cash:           $${data.financials.cash.toLocaleString()}
  Monthly Burn:          $${data.financials.burn.toLocaleString()}
  Runway:                ${data.metrics.runway || 'N/A'} months

================================================================================
                              QUARTERLY HIGHLIGHTS
================================================================================

${data.highlights.map((h, i) => `${i + 1}. ${h}`).join('\n\n')}

================================================================================
                              CHALLENGES & RISKS
================================================================================

${data.challenges.map((c, i) => `${i + 1}. ${c}`).join('\n\n')}

${data.asks && data.asks.length > 0 ? `
================================================================================
                              ASKS FROM THE BOARD
================================================================================

${data.asks.map((a, i) => `${i + 1}. ${a}`).join('\n\n')}
` : ''}

${data.nextQuarterGoals && data.nextQuarterGoals.length > 0 ? `
================================================================================
                              NEXT QUARTER PRIORITIES
================================================================================

${data.nextQuarterGoals.map((g, i) => `${i + 1}. ${g}`).join('\n\n')}
` : ''}

================================================================================
                              APPENDIX
================================================================================

A. Detailed Financial Statements
B. Customer Growth Analysis
C. Product Roadmap
D. Team Updates
E. Cap Table (if applicable)

================================================================================
                              DISCUSSION ITEMS
================================================================================

1. _________________________________________________________________

2. _________________________________________________________________

3. _________________________________________________________________

================================================================================
                              ACTION ITEMS
================================================================================

| Item | Owner | Due Date | Status |
|------|-------|----------|--------|
|      |       |          |        |
|      |       |          |        |
|      |       |          |        |

================================================================================
                           NEXT MEETING
================================================================================

Date: ____________________
Location: ________________
Key Topics: ______________

================================================================================
                    Generated by Alabobai Executive Department
================================================================================
`
  },

  // ============================================================================
  // STRATEGIC PLAN
  // ============================================================================
  strategicPlan: {
    name: 'Strategic Plan',
    description: 'Annual or multi-year strategic planning document',
    fields: ['companyName', 'planPeriod', 'vision', 'mission', 'goals'],
    generate: (data: {
      companyName: string;
      planPeriod: string; // e.g., "2024-2026" or "FY 2024"
      vision: string;
      mission: string;
      values: string[];
      strategicGoals: Array<{
        goal: string;
        description: string;
        initiatives: string[];
        metrics: string[];
        timeline: string;
      }>;
      swotAnalysis?: {
        strengths: string[];
        weaknesses: string[];
        opportunities: string[];
        threats: string[];
      };
    }) => `
================================================================================
${data.companyName.toUpperCase()}
STRATEGIC PLAN
${data.planPeriod}
================================================================================

CONFIDENTIAL - FOR INTERNAL USE ONLY

================================================================================
                              VISION
================================================================================

${data.vision}

================================================================================
                              MISSION
================================================================================

${data.mission}

================================================================================
                              CORE VALUES
================================================================================

${data.values.map((v, i) => `${i + 1}. ${v}`).join('\n\n')}

${data.swotAnalysis ? `
================================================================================
                              SWOT ANALYSIS
================================================================================

STRENGTHS
--------------------------------------------------------------------------------
${data.swotAnalysis.strengths.map(s => `  - ${s}`).join('\n')}

WEAKNESSES
--------------------------------------------------------------------------------
${data.swotAnalysis.weaknesses.map(w => `  - ${w}`).join('\n')}

OPPORTUNITIES
--------------------------------------------------------------------------------
${data.swotAnalysis.opportunities.map(o => `  - ${o}`).join('\n')}

THREATS
--------------------------------------------------------------------------------
${data.swotAnalysis.threats.map(t => `  - ${t}`).join('\n')}
` : ''}

================================================================================
                              STRATEGIC GOALS
================================================================================

${data.strategicGoals.map((sg, index) => `
STRATEGIC GOAL ${index + 1}: ${sg.goal}
================================================================================

Description:
${sg.description}

Timeline: ${sg.timeline}

Key Initiatives:
${sg.initiatives.map((init, i) => `  ${i + 1}. ${init}`).join('\n')}

Success Metrics:
${sg.metrics.map((m, i) => `  ${i + 1}. ${m}`).join('\n')}

Progress Tracking:
[ ] Not Started    [ ] Planning    [ ] In Progress    [ ] Complete

`).join('\n')}

================================================================================
                              IMPLEMENTATION ROADMAP
================================================================================

PHASE 1: FOUNDATION (Months 1-3)
--------------------------------------------------------------------------------
[ ] Communicate strategic plan to all stakeholders
[ ] Align departmental goals with strategic objectives
[ ] Establish tracking mechanisms and KPIs
[ ] Allocate resources and budget

PHASE 2: EXECUTION (Months 4-9)
--------------------------------------------------------------------------------
[ ] Launch key initiatives
[ ] Monthly progress reviews
[ ] Quarterly adjustments as needed
[ ] Document learnings and best practices

PHASE 3: OPTIMIZATION (Months 10-12)
--------------------------------------------------------------------------------
[ ] Evaluate progress against goals
[ ] Identify areas for improvement
[ ] Plan for next planning cycle
[ ] Celebrate achievements

================================================================================
                              RESOURCE REQUIREMENTS
================================================================================

Human Capital:
  - New Hires:    _______________
  - Training:     _______________
  - Consultants:  _______________

Financial:
  - Capital Investment:    $_______________
  - Operating Budget:      $_______________
  - Contingency:           $_______________

Technology:
  - Systems/Tools:  _______________
  - Infrastructure: _______________

================================================================================
                              GOVERNANCE
================================================================================

Strategic Plan Owner: _______________
Executive Sponsor:    _______________

Review Cadence:
  - Monthly: Initiative progress review
  - Quarterly: Strategic goal assessment
  - Annual: Full strategic plan review and update

Communication:
  - All-hands updates: Quarterly
  - Board updates: Quarterly
  - Department updates: Monthly

================================================================================
                              APPROVAL
================================================================================

Prepared By:     _________________________  Date: ____________

CEO:             _________________________  Date: ____________

Board Chair:     _________________________  Date: ____________

================================================================================
                    Generated by Alabobai Executive Department
================================================================================
`
  },

  // ============================================================================
  // EXECUTIVE SUMMARY MEMO
  // ============================================================================
  executiveMemo: {
    name: 'Executive Memo',
    description: 'Formal executive communication memo',
    fields: ['to', 'from', 'subject', 'date', 'content'],
    generate: (data: {
      companyName: string;
      to: string;
      from: string;
      cc?: string[];
      subject: string;
      date: string;
      priority: 'low' | 'normal' | 'high' | 'urgent';
      sections: Array<{
        heading: string;
        content: string;
      }>;
      actionItems?: Array<{
        action: string;
        owner: string;
        dueDate: string;
      }>;
      attachments?: string[];
    }) => `
================================================================================
${data.companyName.toUpperCase()}
EXECUTIVE MEMORANDUM
================================================================================

${data.priority === 'urgent' ? '*** URGENT - IMMEDIATE ATTENTION REQUIRED ***\n' : ''}
${data.priority === 'high' ? '*** HIGH PRIORITY ***\n' : ''}

TO:       ${data.to}
FROM:     ${data.from}
${data.cc && data.cc.length > 0 ? `CC:       ${data.cc.join(', ')}` : ''}
DATE:     ${data.date}
SUBJECT:  ${data.subject}

================================================================================

${data.sections.map(section => `
${section.heading.toUpperCase()}
--------------------------------------------------------------------------------

${section.content}
`).join('\n')}

${data.actionItems && data.actionItems.length > 0 ? `
================================================================================
ACTION ITEMS
================================================================================

| # | Action | Owner | Due Date | Status |
|---|--------|-------|----------|--------|
${data.actionItems.map((item, i) => `| ${i + 1} | ${item.action} | ${item.owner} | ${item.dueDate} | [ ] |`).join('\n')}
` : ''}

${data.attachments && data.attachments.length > 0 ? `
================================================================================
ATTACHMENTS
================================================================================

${data.attachments.map((a, i) => `${i + 1}. ${a}`).join('\n')}
` : ''}

================================================================================

Please direct any questions to the sender.

================================================================================
                    Generated by Alabobai Executive Department
================================================================================
`
  },

  // ============================================================================
  // MEETING AGENDA
  // ============================================================================
  meetingAgenda: {
    name: 'Executive Meeting Agenda',
    description: 'Structured meeting agenda for executive meetings',
    fields: ['meetingTitle', 'date', 'attendees', 'agenda'],
    generate: (data: {
      companyName: string;
      meetingTitle: string;
      date: string;
      time: string;
      duration: string;
      location: string;
      facilitator: string;
      attendees: Array<{ name: string; role?: string }>;
      objectives: string[];
      agendaItems: Array<{
        topic: string;
        presenter: string;
        duration: string;
        type: 'discussion' | 'decision' | 'update' | 'brainstorm';
        materials?: string;
      }>;
      prework?: string[];
    }) => `
================================================================================
${data.companyName.toUpperCase()}
MEETING AGENDA
================================================================================

Meeting:      ${data.meetingTitle}
Date:         ${data.date}
Time:         ${data.time}
Duration:     ${data.duration}
Location:     ${data.location}
Facilitator:  ${data.facilitator}

================================================================================
ATTENDEES
================================================================================

${data.attendees.map(a => `  - ${a.name}${a.role ? ` (${a.role})` : ''}`).join('\n')}

================================================================================
MEETING OBJECTIVES
================================================================================

${data.objectives.map((o, i) => `${i + 1}. ${o}`).join('\n')}

${data.prework && data.prework.length > 0 ? `
================================================================================
PRE-WORK (Please Complete Before Meeting)
================================================================================

${data.prework.map((p, i) => `[ ] ${i + 1}. ${p}`).join('\n')}
` : ''}

================================================================================
AGENDA
================================================================================

| Time | Topic | Presenter | Type | Duration |
|------|-------|-----------|------|----------|
${data.agendaItems.map(item =>
`| ---- | ${item.topic.substring(0, 30).padEnd(30)} | ${item.presenter.padEnd(15)} | ${item.type.padEnd(10)} | ${item.duration} |`
).join('\n')}

--------------------------------------------------------------------------------

DETAILED AGENDA ITEMS
--------------------------------------------------------------------------------

${data.agendaItems.map((item, i) => `
${i + 1}. ${item.topic}
   Presenter:  ${item.presenter}
   Duration:   ${item.duration}
   Type:       ${item.type.toUpperCase()}
   ${item.materials ? `Materials:  ${item.materials}` : ''}

   Discussion Notes:
   ________________________________________________________________
   ________________________________________________________________
   ________________________________________________________________

   Decisions Made:
   ________________________________________________________________

   Action Items:
   [ ] _____________________________________________________________
   [ ] _____________________________________________________________
`).join('\n')}

================================================================================
PARKING LOT (Items for Future Discussion)
================================================================================

1. _______________________________________________________________
2. _______________________________________________________________
3. _______________________________________________________________

================================================================================
NEXT STEPS
================================================================================

Next Meeting Date: _______________
Follow-up Owner:   _______________

================================================================================
                    Generated by Alabobai Executive Department
================================================================================
`
  }
};

export type ExecutiveTemplateKey = keyof typeof EXECUTIVE_TEMPLATES;

export function generateExecutiveDocument(templateKey: ExecutiveTemplateKey, data: any): string {
  const template = EXECUTIVE_TEMPLATES[templateKey];
  if (!template) {
    throw new Error(`Template not found: ${templateKey}`);
  }
  return template.generate(data);
}

export function listExecutiveTemplates() {
  return Object.entries(EXECUTIVE_TEMPLATES).map(([key, value]) => ({
    key,
    name: value.name,
    description: value.description,
    fields: value.fields
  }));
}
