/**
 * Alabobai Finance Department Templates
 * Ready-to-use financial document and calculator generators
 */

export const FINANCE_TEMPLATES = {
  // ============================================================================
  // FINANCIAL PROJECTIONS (5-YEAR)
  // ============================================================================
  financialProjections: {
    name: '5-Year Financial Projections',
    description: 'SaaS/subscription business financial model',
    fields: ['companyName', 'monthlyPrice', 'startingCustomers', 'growthRate', 'churnRate', 'costs'],
    generate: (data: {
      companyName: string;
      monthlyPrice: number;
      startingCustomers: number;
      monthlyGrowthRate: number; // e.g., 0.10 for 10%
      monthlyChurnRate: number; // e.g., 0.05 for 5%
      fixedMonthlyCosts: number;
      variableCostPerCustomer: number;
    }) => {
      const years = 5;
      const projections: any[] = [];

      let customers = data.startingCustomers;

      for (let year = 1; year <= years; year++) {
        let yearlyRevenue = 0;
        let yearlyNewCustomers = 0;
        let yearlyChurnedCustomers = 0;

        for (let month = 1; month <= 12; month++) {
          const newCustomers = Math.floor(customers * data.monthlyGrowthRate);
          const churnedCustomers = Math.floor(customers * data.monthlyChurnRate);

          customers = customers + newCustomers - churnedCustomers;
          yearlyRevenue += customers * data.monthlyPrice;
          yearlyNewCustomers += newCustomers;
          yearlyChurnedCustomers += churnedCustomers;
        }

        const yearlyCosts = (data.fixedMonthlyCosts * 12) + (customers * data.variableCostPerCustomer * 12);
        const netIncome = yearlyRevenue - yearlyCosts;

        projections.push({
          year,
          customers,
          newCustomers: yearlyNewCustomers,
          churnedCustomers: yearlyChurnedCustomers,
          revenue: yearlyRevenue,
          costs: yearlyCosts,
          netIncome,
          margin: (netIncome / yearlyRevenue * 100).toFixed(1)
        });
      }

      return `
${data.companyName.toUpperCase()}
5-YEAR FINANCIAL PROJECTIONS
Generated by Alabobai Finance Department

================================================================================
ASSUMPTIONS
================================================================================

Monthly Subscription Price:     $${data.monthlyPrice}
Starting Customers:             ${data.startingCustomers}
Monthly Customer Growth Rate:   ${(data.monthlyGrowthRate * 100).toFixed(1)}%
Monthly Churn Rate:             ${(data.monthlyChurnRate * 100).toFixed(1)}%
Fixed Monthly Costs:            $${data.fixedMonthlyCosts.toLocaleString()}
Variable Cost per Customer:     $${data.variableCostPerCustomer}

================================================================================
PROJECTED FINANCIALS
================================================================================

${projections.map(p => `
YEAR ${p.year}
────────────────────────────────────────────────────────────────────────────────
Ending Customers:        ${p.customers.toLocaleString()}
New Customers (Year):    ${p.newCustomers.toLocaleString()}
Churned Customers:       ${p.churnedCustomers.toLocaleString()}

Revenue:                 $${p.revenue.toLocaleString()}
Costs:                   $${p.costs.toLocaleString()}
Net Income:              $${p.netIncome.toLocaleString()}
Profit Margin:           ${p.margin}%
`).join('\n')}

================================================================================
5-YEAR SUMMARY
================================================================================

                    Year 1          Year 2          Year 3          Year 4          Year 5
Customers           ${projections.map(p => p.customers.toLocaleString().padStart(10)).join('      ')}
Revenue             ${projections.map(p => ('$' + (p.revenue/1000).toFixed(0) + 'K').padStart(10)).join('      ')}
Net Income          ${projections.map(p => ('$' + (p.netIncome/1000).toFixed(0) + 'K').padStart(10)).join('      ')}

================================================================================
KEY METRICS
================================================================================

Annual Recurring Revenue (ARR) by Year 5:  $${(projections[4].customers * data.monthlyPrice * 12).toLocaleString()}
Monthly Recurring Revenue (MRR) by Year 5: $${(projections[4].customers * data.monthlyPrice).toLocaleString()}
Customer Lifetime Value (LTV):             $${(data.monthlyPrice / data.monthlyChurnRate).toFixed(2)}
Customer Acquisition Cost Target:          $${(data.monthlyPrice / data.monthlyChurnRate * 0.33).toFixed(2)} (LTV:CAC 3:1)

================================================================================
NOTES
================================================================================

1. These projections assume consistent growth and churn rates. Actual results may vary.
2. Adjust growth rate based on marketing spend and market conditions.
3. Churn rate typically decreases as product matures.
4. Consider seasonal variations not reflected in this model.
5. Consult with a CPA for tax planning based on these projections.

Generated on: ${new Date().toISOString().split('T')[0]}
`;
    }
  },

  // ============================================================================
  // PROFESSIONAL INVOICE
  // ============================================================================
  invoice: {
    name: 'Professional Invoice',
    description: 'Clean, professional invoice template',
    fields: ['companyInfo', 'clientInfo', 'items', 'dueDate'],
    generate: (data: {
      companyName: string;
      companyAddress: string;
      companyEmail: string;
      companyPhone: string;
      clientName: string;
      clientAddress: string;
      clientEmail: string;
      invoiceNumber: string;
      invoiceDate: string;
      dueDate: string;
      items: Array<{ description: string; quantity: number; rate: number }>;
      notes?: string;
      taxRate?: number;
    }) => {
      const subtotal = data.items.reduce((sum, item) => sum + (item.quantity * item.rate), 0);
      const tax = data.taxRate ? subtotal * data.taxRate : 0;
      const total = subtotal + tax;

      return `
================================================================================
                                   INVOICE
================================================================================

FROM:                                       BILL TO:
${data.companyName}                         ${data.clientName}
${data.companyAddress}                      ${data.clientAddress}
${data.companyEmail}                        ${data.clientEmail}
${data.companyPhone}

================================================================================

Invoice Number:    ${data.invoiceNumber}
Invoice Date:      ${data.invoiceDate}
Due Date:          ${data.dueDate}
Payment Terms:     Due on receipt

================================================================================
                                 LINE ITEMS
================================================================================

Description                                     Qty        Rate        Amount
--------------------------------------------------------------------------------
${data.items.map(item =>
  `${item.description.padEnd(45)} ${item.quantity.toString().padStart(5)}    $${item.rate.toFixed(2).padStart(8)}    $${(item.quantity * item.rate).toFixed(2).padStart(10)}`
).join('\n')}

--------------------------------------------------------------------------------
                                                          Subtotal:  $${subtotal.toFixed(2).padStart(10)}
${data.taxRate ? `                                                          Tax (${(data.taxRate * 100).toFixed(0)}%):    $${tax.toFixed(2).padStart(10)}` : ''}
                                                          ─────────────────────
                                                          TOTAL:     $${total.toFixed(2).padStart(10)}

================================================================================
                               PAYMENT METHODS
================================================================================

Bank Transfer:
  Bank: [Your Bank Name]
  Account: [Account Number]
  Routing: [Routing Number]

Online Payment:
  Pay securely at: [Your Payment Link]

================================================================================

${data.notes ? `NOTES:\n${data.notes}\n\n` : ''}Thank you for your business!

================================================================================
`;
    }
  },

  // ============================================================================
  // PROFIT & LOSS STATEMENT
  // ============================================================================
  profitLoss: {
    name: 'Profit & Loss Statement',
    description: 'Monthly/quarterly P&L statement',
    fields: ['companyName', 'period', 'revenue', 'expenses'],
    generate: (data: {
      companyName: string;
      periodStart: string;
      periodEnd: string;
      revenue: Array<{ category: string; amount: number }>;
      costOfSales: Array<{ category: string; amount: number }>;
      operatingExpenses: Array<{ category: string; amount: number }>;
      otherIncome?: Array<{ category: string; amount: number }>;
      otherExpenses?: Array<{ category: string; amount: number }>;
    }) => {
      const totalRevenue = data.revenue.reduce((sum, r) => sum + r.amount, 0);
      const totalCOS = data.costOfSales.reduce((sum, c) => sum + c.amount, 0);
      const grossProfit = totalRevenue - totalCOS;
      const totalOpEx = data.operatingExpenses.reduce((sum, e) => sum + e.amount, 0);
      const operatingIncome = grossProfit - totalOpEx;
      const totalOtherIncome = data.otherIncome?.reduce((sum, i) => sum + i.amount, 0) || 0;
      const totalOtherExpenses = data.otherExpenses?.reduce((sum, e) => sum + e.amount, 0) || 0;
      const netIncome = operatingIncome + totalOtherIncome - totalOtherExpenses;

      const formatMoney = (amount: number) => {
        const formatted = Math.abs(amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
        return amount < 0 ? `($${formatted})` : `$${formatted}`;
      };

      return `
================================================================================
${data.companyName.toUpperCase()}
PROFIT AND LOSS STATEMENT
For the Period ${data.periodStart} to ${data.periodEnd}
================================================================================

REVENUE
--------------------------------------------------------------------------------
${data.revenue.map(r => `  ${r.category.padEnd(50)} ${formatMoney(r.amount).padStart(15)}`).join('\n')}
--------------------------------------------------------------------------------
  TOTAL REVENUE                                         ${formatMoney(totalRevenue).padStart(15)}

COST OF SALES
--------------------------------------------------------------------------------
${data.costOfSales.map(c => `  ${c.category.padEnd(50)} ${formatMoney(c.amount).padStart(15)}`).join('\n')}
--------------------------------------------------------------------------------
  TOTAL COST OF SALES                                   ${formatMoney(totalCOS).padStart(15)}

================================================================================
  GROSS PROFIT                                          ${formatMoney(grossProfit).padStart(15)}
  Gross Margin                                          ${((grossProfit / totalRevenue) * 100).toFixed(1).padStart(14)}%
================================================================================

OPERATING EXPENSES
--------------------------------------------------------------------------------
${data.operatingExpenses.map(e => `  ${e.category.padEnd(50)} ${formatMoney(e.amount).padStart(15)}`).join('\n')}
--------------------------------------------------------------------------------
  TOTAL OPERATING EXPENSES                              ${formatMoney(totalOpEx).padStart(15)}

================================================================================
  OPERATING INCOME                                      ${formatMoney(operatingIncome).padStart(15)}
================================================================================

${data.otherIncome && data.otherIncome.length > 0 ? `
OTHER INCOME
--------------------------------------------------------------------------------
${data.otherIncome.map(i => `  ${i.category.padEnd(50)} ${formatMoney(i.amount).padStart(15)}`).join('\n')}
--------------------------------------------------------------------------------
  TOTAL OTHER INCOME                                    ${formatMoney(totalOtherIncome).padStart(15)}
` : ''}

${data.otherExpenses && data.otherExpenses.length > 0 ? `
OTHER EXPENSES
--------------------------------------------------------------------------------
${data.otherExpenses.map(e => `  ${e.category.padEnd(50)} ${formatMoney(e.amount).padStart(15)}`).join('\n')}
--------------------------------------------------------------------------------
  TOTAL OTHER EXPENSES                                  ${formatMoney(totalOtherExpenses).padStart(15)}
` : ''}

================================================================================
  NET INCOME                                            ${formatMoney(netIncome).padStart(15)}
  Net Margin                                            ${((netIncome / totalRevenue) * 100).toFixed(1).padStart(14)}%
================================================================================

Generated on: ${new Date().toISOString().split('T')[0]}
This statement is for internal use. Consult a CPA for official financial statements.
`;
    }
  },

  // ============================================================================
  // CASH FLOW FORECAST
  // ============================================================================
  cashFlowForecast: {
    name: 'Cash Flow Forecast',
    description: '12-month cash flow projection',
    fields: ['companyName', 'startingCash', 'monthlyInflows', 'monthlyOutflows'],
    generate: (data: {
      companyName: string;
      startingCash: number;
      months: Array<{
        month: string;
        inflows: { revenue: number; investments?: number; loans?: number; other?: number };
        outflows: { payroll: number; rent: number; marketing: number; software: number; other: number };
      }>;
    }) => {
      let runningCash = data.startingCash;
      const forecast = data.months.map(m => {
        const totalInflows = m.inflows.revenue + (m.inflows.investments || 0) + (m.inflows.loans || 0) + (m.inflows.other || 0);
        const totalOutflows = m.outflows.payroll + m.outflows.rent + m.outflows.marketing + m.outflows.software + m.outflows.other;
        const netCashFlow = totalInflows - totalOutflows;
        runningCash += netCashFlow;
        return {
          month: m.month,
          totalInflows,
          totalOutflows,
          netCashFlow,
          endingCash: runningCash,
          ...m.inflows,
          ...m.outflows
        };
      });

      const formatMoney = (amount: number) => {
        const formatted = Math.abs(amount).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
        return amount < 0 ? `(${formatted})` : formatted;
      };

      return `
================================================================================
${data.companyName.toUpperCase()}
12-MONTH CASH FLOW FORECAST
================================================================================

Starting Cash Balance: $${data.startingCash.toLocaleString()}

================================================================================
MONTHLY CASH FLOW SUMMARY
================================================================================

Month           Inflows      Outflows     Net Flow     Ending Cash
--------------------------------------------------------------------------------
${forecast.map(f =>
  `${f.month.padEnd(12)}    $${formatMoney(f.totalInflows).padStart(8)}    $${formatMoney(f.totalOutflows).padStart(8)}    $${formatMoney(f.netCashFlow).padStart(8)}    $${formatMoney(f.endingCash).padStart(10)}`
).join('\n')}
--------------------------------------------------------------------------------

================================================================================
DETAILED BREAKDOWN
================================================================================

${forecast.map(f => `
${f.month}
  INFLOWS:
    Revenue:           $${formatMoney(f.revenue).padStart(10)}
    Investments:       $${formatMoney(f.investments || 0).padStart(10)}
    Loans:             $${formatMoney(f.loans || 0).padStart(10)}
    Other:             $${formatMoney(f.other || 0).padStart(10)}
    ────────────────────────────
    Total Inflows:     $${formatMoney(f.totalInflows).padStart(10)}

  OUTFLOWS:
    Payroll:           $${formatMoney(f.payroll).padStart(10)}
    Rent:              $${formatMoney(f.rent).padStart(10)}
    Marketing:         $${formatMoney(f.marketing).padStart(10)}
    Software:          $${formatMoney(f.software).padStart(10)}
    Other:             $${formatMoney(f.other).padStart(10)}
    ────────────────────────────
    Total Outflows:    $${formatMoney(f.totalOutflows).padStart(10)}

  NET CASH FLOW:       $${formatMoney(f.netCashFlow).padStart(10)}
  ENDING BALANCE:      $${formatMoney(f.endingCash).padStart(10)}
`).join('\n')}

================================================================================
KEY INSIGHTS
================================================================================

Lowest Cash Point:    $${formatMoney(Math.min(...forecast.map(f => f.endingCash)))} (${forecast.find(f => f.endingCash === Math.min(...forecast.map(f => f.endingCash)))?.month})
Highest Cash Point:   $${formatMoney(Math.max(...forecast.map(f => f.endingCash)))} (${forecast.find(f => f.endingCash === Math.max(...forecast.map(f => f.endingCash)))?.month})
Average Monthly Burn: $${formatMoney(forecast.reduce((sum, f) => sum + (f.totalOutflows - f.totalInflows), 0) / forecast.length)}
Months of Runway:     ${data.startingCash > 0 ? Math.floor(data.startingCash / (forecast.reduce((sum, f) => sum + f.totalOutflows, 0) / forecast.length)) : 0}

${forecast.some(f => f.endingCash < 0) ? `
WARNING: Negative cash balance projected in: ${forecast.filter(f => f.endingCash < 0).map(f => f.month).join(', ')}
Consider reducing expenses or securing additional funding.
` : ''}

================================================================================
Generated on: ${new Date().toISOString().split('T')[0]}
This forecast is for planning purposes. Actual results may vary.
================================================================================
`;
    }
  },

  // ============================================================================
  // TAX DEDUCTION CHECKLIST
  // ============================================================================
  taxDeductions: {
    name: 'Tax Deduction Checklist',
    description: 'Common business tax deductions tracker',
    fields: ['businessType'],
    generate: (data: {
      businessType: 'saas' | 'ecommerce' | 'services' | 'consulting';
      year: number;
    }) => `
================================================================================
BUSINESS TAX DEDUCTION CHECKLIST
Tax Year: ${data.year}
Business Type: ${data.businessType.toUpperCase()}
================================================================================

IMPORTANT: This checklist is for informational purposes only. Consult a licensed
CPA or tax professional for advice specific to your situation.

================================================================================
COMMON BUSINESS DEDUCTIONS
================================================================================

HOME OFFICE DEDUCTION
[ ] Square footage of dedicated workspace: _____ sq ft
[ ] Total home square footage: _____ sq ft
[ ] Home office percentage: _____%
[ ] Rent/Mortgage interest (proportional)
[ ] Utilities (proportional)
[ ] Internet (proportional)
[ ] Home insurance (proportional)

SOFTWARE & SUBSCRIPTIONS                                    Amount
--------------------------------------------------------------------------------
[ ] Hosting services (AWS, Vercel, etc.)                   $_________
[ ] Development tools (GitHub, IDEs)                       $_________
[ ] Design tools (Figma, Adobe)                            $_________
[ ] Project management (Notion, Asana)                     $_________
[ ] Communication (Slack, Zoom)                            $_________
[ ] Email marketing (Mailchimp, etc.)                      $_________
[ ] Analytics (Mixpanel, Amplitude)                        $_________
[ ] Customer support (Intercom, Zendesk)                   $_________
[ ] Accounting software (QuickBooks, etc.)                 $_________
[ ] Other subscriptions                                    $_________

EQUIPMENT & TECHNOLOGY
[ ] Computer equipment                                     $_________
[ ] Monitors and peripherals                               $_________
[ ] Mobile devices (business use %)                        $_________
[ ] Office furniture                                       $_________
[ ] Other equipment                                        $_________

PROFESSIONAL SERVICES
[ ] Legal fees                                             $_________
[ ] Accounting/CPA fees                                    $_________
[ ] Consulting fees                                        $_________
[ ] Contractor payments (Issue 1099s!)                     $_________

MARKETING & ADVERTISING
[ ] Digital advertising (Facebook, Google)                 $_________
[ ] Content creation                                       $_________
[ ] Website development                                    $_________
[ ] Branding and design                                    $_________
[ ] Events and sponsorships                                $_________

TRAVEL & MEALS (Business Purpose Only)
[ ] Airfare                                                $_________
[ ] Hotels                                                 $_________
[ ] Ground transportation                                  $_________
[ ] Business meals (50% deductible)                        $_________
[ ] Conference registration                                $_________

EDUCATION & PROFESSIONAL DEVELOPMENT
[ ] Online courses (business-related)                      $_________
[ ] Books and publications                                 $_________
[ ] Conference attendance                                  $_________
[ ] Professional memberships                               $_________

INSURANCE
[ ] Business liability insurance                           $_________
[ ] Errors & omissions insurance                           $_________
[ ] Health insurance (self-employed)                       $_________
[ ] Cyber liability insurance                              $_________

BANKING & FINANCE
[ ] Business credit card fees                              $_________
[ ] Bank service charges                                   $_________
[ ] Payment processing fees                                $_________
[ ] Interest on business loans                             $_________

RETIREMENT CONTRIBUTIONS
[ ] SEP-IRA (up to 25% of net self-employment income)     $_________
[ ] Solo 401(k) (up to $66,000 for 2024)                  $_________

================================================================================
QUARTERLY TAX ESTIMATES
================================================================================

Due Dates for ${data.year}:
[ ] Q1: April 15 - Amount paid: $_________
[ ] Q2: June 15 - Amount paid: $_________
[ ] Q3: September 15 - Amount paid: $_________
[ ] Q4: January 15 (next year) - Amount paid: $_________

================================================================================
RECORDS TO KEEP
================================================================================

[ ] All receipts over $75 (keep digital copies)
[ ] Bank statements
[ ] Credit card statements
[ ] Invoices issued
[ ] Contracts and agreements
[ ] Mileage log (if applicable)
[ ] Home office measurements and photos

================================================================================
IMPORTANT DEADLINES
================================================================================

March 15: S-Corp and Partnership returns due
April 15: Individual and C-Corp returns due
          Q1 estimated taxes due
June 15:  Q2 estimated taxes due
September 15: Q3 estimated taxes due
              Extension deadline for S-Corps/Partnerships
October 15: Extension deadline for individuals/C-Corps

================================================================================

TOTAL ESTIMATED DEDUCTIONS: $_____________

DISCLAIMER: This checklist is for informational purposes only and does not
constitute tax advice. Tax laws change frequently. Always consult with a
qualified tax professional before making tax decisions.

Generated by Alabobai Finance Department
${new Date().toISOString().split('T')[0]}
================================================================================
`
  }
};

export type FinanceTemplateKey = keyof typeof FINANCE_TEMPLATES;

export function generateFinanceDocument(templateKey: FinanceTemplateKey, data: any): string {
  const template = FINANCE_TEMPLATES[templateKey];
  if (!template) {
    throw new Error(`Template not found: ${templateKey}`);
  }
  return template.generate(data);
}

export function listFinanceTemplates() {
  return Object.entries(FINANCE_TEMPLATES).map(([key, value]) => ({
    key,
    name: value.name,
    description: value.description,
    fields: value.fields
  }));
}
