/**
 * Alabobai Funding Department Templates
 * Pitch Decks, Grant Applications, Investment Documents
 */

export const FUNDING_TEMPLATES = {
  // ============================================================================
  // PITCH DECK OUTLINE
  // ============================================================================
  pitchDeck: {
    name: 'Pitch Deck Outline',
    description: 'Investor pitch deck structure and content',
    fields: ['companyName', 'tagline', 'problem', 'solution', 'market', 'business', 'team', 'financials', 'ask'],
    generate: (data: {
      companyName: string;
      tagline: string;
      problem: {
        statement: string;
        painPoints: string[];
        currentSolutions: string;
      };
      solution: {
        description: string;
        keyFeatures: string[];
        uniqueValue: string;
      };
      market: {
        tam: string;
        sam: string;
        som: string;
        trends: string[];
      };
      businessModel: {
        model: string;
        pricing: string;
        unitEconomics?: {
          cac?: string;
          ltv?: string;
          payback?: string;
        };
      };
      traction: {
        metrics: Array<{ metric: string; value: string }>;
        milestones: string[];
        customers?: string[];
      };
      competition: Array<{
        competitor: string;
        differentiation: string;
      }>;
      team: Array<{
        name: string;
        role: string;
        background: string;
      }>;
      financials: {
        revenue?: string;
        growth?: string;
        projections: string;
      };
      ask: {
        amount: string;
        use: string[];
        timeline: string;
      };
    }) => `
================================================================================
${data.companyName.toUpperCase()}
INVESTOR PITCH DECK
================================================================================

"${data.tagline}"

Generated by Alabobai Funding Department
Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

================================================================================
SLIDE 1: TITLE
================================================================================

${data.companyName}

"${data.tagline}"

[Company Logo]

[Contact Information]

================================================================================
SLIDE 2: THE PROBLEM
================================================================================

${data.problem.statement}

Pain Points:
${data.problem.painPoints.map((p, i) => `  ${i + 1}. ${p}`).join('\n')}

Current Solutions Fall Short:
${data.problem.currentSolutions}

================================================================================
SLIDE 3: THE SOLUTION
================================================================================

${data.solution.description}

Key Features:
${data.solution.keyFeatures.map((f, i) => `  ${i + 1}. ${f}`).join('\n')}

Unique Value Proposition:
${data.solution.uniqueValue}

================================================================================
SLIDE 4: PRODUCT DEMO / HOW IT WORKS
================================================================================

[Include screenshots, demo video, or product walkthrough]

Step 1: _______________
Step 2: _______________
Step 3: _______________

================================================================================
SLIDE 5: MARKET OPPORTUNITY
================================================================================

Total Addressable Market (TAM):    ${data.market.tam}
Serviceable Addressable Market (SAM): ${data.market.sam}
Serviceable Obtainable Market (SOM): ${data.market.som}

Market Trends:
${data.market.trends.map((t, i) => `  ${i + 1}. ${t}`).join('\n')}

[Include market size visualization]

================================================================================
SLIDE 6: BUSINESS MODEL
================================================================================

Model: ${data.businessModel.model}

Pricing: ${data.businessModel.pricing}

${data.businessModel.unitEconomics ? `
Unit Economics:
  Customer Acquisition Cost (CAC):  ${data.businessModel.unitEconomics.cac || 'TBD'}
  Lifetime Value (LTV):             ${data.businessModel.unitEconomics.ltv || 'TBD'}
  LTV:CAC Ratio:                    ${data.businessModel.unitEconomics.ltv && data.businessModel.unitEconomics.cac ? 'Calculate' : 'TBD'}
  Payback Period:                   ${data.businessModel.unitEconomics.payback || 'TBD'}
` : ''}

================================================================================
SLIDE 7: TRACTION
================================================================================

Key Metrics:
${data.traction.metrics.map(m => `  ${m.metric}: ${m.value}`).join('\n')}

Key Milestones:
${data.traction.milestones.map((m, i) => `  ${i + 1}. ${m}`).join('\n')}

${data.traction.customers && data.traction.customers.length > 0 ? `
Notable Customers:
${data.traction.customers.map(c => `  - ${c}`).join('\n')}
` : ''}

[Include growth chart]

================================================================================
SLIDE 8: COMPETITION
================================================================================

Competitive Landscape:

| Competitor | Our Differentiation |
|------------|---------------------|
${data.competition.map(c => `| ${c.competitor.padEnd(20)} | ${c.differentiation} |`).join('\n')}

Why We Win:
  1. _______________
  2. _______________
  3. _______________

[Include competitive matrix visualization]

================================================================================
SLIDE 9: GO-TO-MARKET STRATEGY
================================================================================

Target Customers:
  Primary:   _______________
  Secondary: _______________

Acquisition Channels:
  1. _______________
  2. _______________
  3. _______________

Growth Strategy:
  Phase 1: _______________
  Phase 2: _______________
  Phase 3: _______________

================================================================================
SLIDE 10: TEAM
================================================================================

${data.team.map(member => `
${member.name} - ${member.role}
${member.background}
`).join('\n')}

Advisors:
  - _______________
  - _______________

[Include team photos]

================================================================================
SLIDE 11: FINANCIALS
================================================================================

${data.financials.revenue ? `Current Revenue: ${data.financials.revenue}` : ''}
${data.financials.growth ? `Growth Rate: ${data.financials.growth}` : ''}

Projections:
${data.financials.projections}

[Include financial projections chart]

                    Year 1      Year 2      Year 3      Year 4      Year 5
Revenue             $______     $______     $______     $______     $______
Customers           ______      ______      ______      ______      ______
Gross Margin        ____%       ____%       ____%       ____%       ____%

================================================================================
SLIDE 12: THE ASK
================================================================================

Raising: ${data.ask.amount}

Use of Funds:
${data.ask.use.map((u, i) => `  ${i + 1}. ${u}`).join('\n')}

Timeline: ${data.ask.timeline}

[Include pie chart of fund allocation]

================================================================================
SLIDE 13: VISION / CLOSING
================================================================================

Our Vision:
_______________________________________________________________
_______________________________________________________________

Why Now:
_______________________________________________________________

Why Us:
_______________________________________________________________

================================================================================
SLIDE 14: APPENDIX
================================================================================

Additional materials available:
  - Detailed financial model
  - Customer case studies
  - Product roadmap
  - Technical architecture
  - Market research

================================================================================
CONTACT INFORMATION
================================================================================

${data.companyName}

Website:  _______________
Email:    _______________
Phone:    _______________
Address:  _______________

================================================================================
                    Generated by Alabobai Funding Department
================================================================================
`
  },

  // ============================================================================
  // GRANT APPLICATION
  // ============================================================================
  grantApplication: {
    name: 'Grant Application',
    description: 'Template for research and business grants',
    fields: ['organizationName', 'projectTitle', 'grantProgram', 'amount', 'project'],
    generate: (data: {
      organizationName: string;
      projectTitle: string;
      grantProgram: string;
      grantingOrganization: string;
      requestedAmount: number;
      projectDuration: string;
      principalInvestigator: {
        name: string;
        title: string;
        email: string;
        phone: string;
      };
      executiveSummary: string;
      problemStatement: string;
      objectives: string[];
      methodology: string;
      timeline: Array<{
        phase: string;
        duration: string;
        activities: string[];
        deliverables: string[];
      }>;
      budget: Array<{
        category: string;
        amount: number;
        justification: string;
      }>;
      expectedOutcomes: string[];
      evaluationPlan: string;
      sustainability: string;
      organizationBackground: string;
    }) => {
      const totalBudget = data.budget.reduce((sum, b) => sum + b.amount, 0);

      return `
================================================================================
GRANT APPLICATION
================================================================================

Grant Program:          ${data.grantProgram}
Granting Organization:  ${data.grantingOrganization}
Submission Date:        ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

================================================================================
APPLICANT INFORMATION
================================================================================

Organization Name:      ${data.organizationName}
Project Title:          ${data.projectTitle}
Requested Amount:       $${data.requestedAmount.toLocaleString()}
Project Duration:       ${data.projectDuration}

Principal Investigator / Project Lead:
  Name:   ${data.principalInvestigator.name}
  Title:  ${data.principalInvestigator.title}
  Email:  ${data.principalInvestigator.email}
  Phone:  ${data.principalInvestigator.phone}

================================================================================
EXECUTIVE SUMMARY
================================================================================

${data.executiveSummary}

================================================================================
STATEMENT OF NEED / PROBLEM STATEMENT
================================================================================

${data.problemStatement}

================================================================================
PROJECT OBJECTIVES
================================================================================

${data.objectives.map((obj, i) => `
Objective ${i + 1}: ${obj}
`).join('\n')}

================================================================================
METHODOLOGY / APPROACH
================================================================================

${data.methodology}

================================================================================
PROJECT TIMELINE
================================================================================

${data.timeline.map((phase, i) => `
PHASE ${i + 1}: ${phase.phase}
Duration: ${phase.duration}
--------------------------------------------------------------------------------

Activities:
${phase.activities.map((a, j) => `  ${j + 1}. ${a}`).join('\n')}

Deliverables:
${phase.deliverables.map((d, j) => `  ${j + 1}. ${d}`).join('\n')}
`).join('\n')}

================================================================================
BUDGET
================================================================================

| Category | Amount | % of Total |
|----------|--------|------------|
${data.budget.map(b =>
`| ${b.category.padEnd(30)} | $${b.amount.toLocaleString().padStart(10)} | ${((b.amount / totalBudget) * 100).toFixed(1).padStart(8)}% |`
).join('\n')}
|--------------------------------|------------|------------|
| TOTAL                          | $${totalBudget.toLocaleString().padStart(10)} |    100.0% |

BUDGET JUSTIFICATION
--------------------------------------------------------------------------------

${data.budget.map(b => `
${b.category}: $${b.amount.toLocaleString()}
${b.justification}
`).join('\n')}

================================================================================
EXPECTED OUTCOMES AND IMPACT
================================================================================

${data.expectedOutcomes.map((outcome, i) => `${i + 1}. ${outcome}`).join('\n\n')}

================================================================================
EVALUATION PLAN
================================================================================

${data.evaluationPlan}

================================================================================
SUSTAINABILITY PLAN
================================================================================

${data.sustainability}

================================================================================
ORGANIZATIONAL BACKGROUND AND CAPACITY
================================================================================

${data.organizationBackground}

================================================================================
ATTACHMENTS CHECKLIST
================================================================================

[ ] IRS Determination Letter (501(c)(3) status)
[ ] Current year budget
[ ] Most recent audited financial statements
[ ] List of Board of Directors
[ ] Key staff resumes/CVs
[ ] Letters of support (if applicable)
[ ] Prior grant reports (if applicable)

================================================================================
CERTIFICATION
================================================================================

I certify that the information provided in this application is true and
accurate to the best of my knowledge. I understand that any false statements
may result in disqualification or termination of the grant.

Authorized Signature: _______________________________

Printed Name:         _______________________________

Title:                _______________________________

Date:                 _______________________________

================================================================================
                    Generated by Alabobai Funding Department
================================================================================
`;
    }
  },

  // ============================================================================
  // INVESTOR TERM SHEET
  // ============================================================================
  termSheet: {
    name: 'Term Sheet',
    description: 'Non-binding investment term sheet',
    fields: ['companyName', 'investor', 'amount', 'valuation', 'terms'],
    generate: (data: {
      companyName: string;
      investorName: string;
      roundType: 'Pre-Seed' | 'Seed' | 'Series A' | 'Series B' | 'Series C' | 'Bridge';
      investmentAmount: number;
      preMoneyValuation: number;
      securityType: 'Common Stock' | 'Preferred Stock' | 'SAFE' | 'Convertible Note';
      terms: {
        liquidationPreference?: string;
        antiDilution?: string;
        dividends?: string;
        votingRights?: string;
        boardSeats?: string;
        proRataRights?: boolean;
        informationRights?: boolean;
        dragAlong?: boolean;
        tagAlong?: boolean;
      };
      closingConditions?: string[];
      exclusivityPeriod?: string;
      expirationDate: string;
    }) => {
      const postMoneyValuation = data.preMoneyValuation + data.investmentAmount;
      const ownershipPercentage = (data.investmentAmount / postMoneyValuation) * 100;

      return `
================================================================================
TERM SHEET
${data.roundType.toUpperCase()} FINANCING
================================================================================

THIS TERM SHEET IS NON-BINDING AND IS SUBJECT TO THE EXECUTION OF DEFINITIVE
AGREEMENTS. THIS TERM SHEET DOES NOT CREATE ANY LEGALLY BINDING OBLIGATIONS.

Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
Expiration: ${data.expirationDate}

================================================================================
PARTIES
================================================================================

Company:    ${data.companyName} (the "Company")
Investor:   ${data.investorName} (the "Investor")

================================================================================
OFFERING TERMS
================================================================================

Security:               ${data.securityType}
Round Type:             ${data.roundType}
Investment Amount:      $${data.investmentAmount.toLocaleString()}
Pre-Money Valuation:    $${data.preMoneyValuation.toLocaleString()}
Post-Money Valuation:   $${postMoneyValuation.toLocaleString()}
Ownership Percentage:   ${ownershipPercentage.toFixed(2)}%

================================================================================
KEY TERMS
================================================================================

${data.terms.liquidationPreference ? `
LIQUIDATION PREFERENCE
--------------------------------------------------------------------------------
${data.terms.liquidationPreference}
` : ''}

${data.terms.antiDilution ? `
ANTI-DILUTION PROTECTION
--------------------------------------------------------------------------------
${data.terms.antiDilution}
` : ''}

${data.terms.dividends ? `
DIVIDENDS
--------------------------------------------------------------------------------
${data.terms.dividends}
` : ''}

${data.terms.votingRights ? `
VOTING RIGHTS
--------------------------------------------------------------------------------
${data.terms.votingRights}
` : ''}

${data.terms.boardSeats ? `
BOARD COMPOSITION
--------------------------------------------------------------------------------
${data.terms.boardSeats}
` : ''}

================================================================================
INVESTOR RIGHTS
================================================================================

Pro-Rata Rights:      ${data.terms.proRataRights ? 'Yes - Investor shall have the right to participate in future financing rounds' : 'No'}

Information Rights:   ${data.terms.informationRights ? 'Yes - Company shall provide quarterly financial statements and annual audited financials' : 'No'}

================================================================================
PROTECTIVE PROVISIONS
================================================================================

Drag-Along Rights:    ${data.terms.dragAlong ? 'Yes' : 'No'}
Tag-Along Rights:     ${data.terms.tagAlong ? 'Yes' : 'No'}

================================================================================
VESTING
================================================================================

Founder Vesting:      All founders shall be subject to 4-year vesting with
                      1-year cliff. [__]% of shares will be vested as of
                      closing based on time served.

================================================================================
EMPLOYEE OPTION POOL
================================================================================

The Company shall reserve [__]% of the fully diluted capitalization for
employee stock options. The option pool shall be created from pre-money
shares.

${data.closingConditions && data.closingConditions.length > 0 ? `
================================================================================
CLOSING CONDITIONS
================================================================================

${data.closingConditions.map((c, i) => `${i + 1}. ${c}`).join('\n')}
` : ''}

${data.exclusivityPeriod ? `
================================================================================
EXCLUSIVITY
================================================================================

The Company agrees not to solicit, encourage, or accept any other investment
offers for a period of ${data.exclusivityPeriod} from the date of this
term sheet.
` : ''}

================================================================================
EXPENSES
================================================================================

The Company shall pay the Investor's reasonable legal fees and expenses
incurred in connection with this transaction, up to a maximum of $[____].

================================================================================
CONFIDENTIALITY
================================================================================

This term sheet and its contents are confidential and may not be disclosed
to any third party without the prior written consent of both parties, except
to legal and financial advisors.

================================================================================
GOVERNING LAW
================================================================================

This term sheet and any definitive agreements shall be governed by the laws
of the State of Delaware.

================================================================================
NON-BINDING
================================================================================

This term sheet is intended solely as a basis for further discussion and is
not intended to be and does not constitute a legally binding obligation.
No legally binding obligation will be created, implied, or inferred until
definitive agreements are executed and delivered by all parties.

================================================================================
SIGNATURES
================================================================================

For the Company:

_________________________________________
Name:
Title:
Date:


For the Investor:

_________________________________________
Name:
Title:
Date:

================================================================================
                    Generated by Alabobai Funding Department
================================================================================
`;
    }
  },

  // ============================================================================
  // SAFE AGREEMENT
  // ============================================================================
  safeAgreement: {
    name: 'SAFE Agreement',
    description: 'Simple Agreement for Future Equity (YC Standard)',
    fields: ['companyName', 'investorName', 'amount', 'valuationCap', 'discount'],
    generate: (data: {
      companyName: string;
      companyState: string;
      investorName: string;
      investmentAmount: number;
      valuationCap?: number;
      discountRate?: number;
      safeType: 'Valuation Cap Only' | 'Discount Only' | 'Valuation Cap and Discount' | 'MFN';
      effectiveDate: string;
    }) => `
================================================================================
SAFE
(SIMPLE AGREEMENT FOR FUTURE EQUITY)
================================================================================

THIS INSTRUMENT AND ANY SECURITIES ISSUABLE PURSUANT HERETO HAVE NOT BEEN
REGISTERED UNDER THE SECURITIES ACT OF 1933, AS AMENDED, OR UNDER ANY STATE
SECURITIES LAWS.

================================================================================
PARTIES
================================================================================

Company:    ${data.companyName}
            a ${data.companyState} corporation (the "Company")

Investor:   ${data.investorName} (the "Investor")

Date:       ${data.effectiveDate}

================================================================================
RECITALS
================================================================================

The Company is issuing this SAFE to the Investor in exchange for the payment
by the Investor of $${data.investmentAmount.toLocaleString()} (the "Purchase Amount")
on or about the date of this SAFE.

SAFE Type: ${data.safeType}

================================================================================
TERMS
================================================================================

PURCHASE AMOUNT:    $${data.investmentAmount.toLocaleString()}

${data.valuationCap ? `VALUATION CAP:      $${data.valuationCap.toLocaleString()}` : ''}

${data.discountRate ? `DISCOUNT RATE:      ${data.discountRate}%
DISCOUNT PRICE:     The price per share equal to the price paid per share
                    in the Equity Financing multiplied by ${(100 - data.discountRate) / 100}` : ''}

================================================================================
1. EVENTS
================================================================================

1.1 EQUITY FINANCING

If there is an Equity Financing before the termination of this SAFE, on the
initial closing of such Equity Financing, this SAFE will automatically
convert into the number of shares of Safe Preferred Stock equal to the
Purchase Amount divided by the Conversion Price.

${data.valuationCap && data.discountRate ? `
The Conversion Price shall be the lower of:
(a) the Discount Price, or
(b) the price per share equal to the Valuation Cap divided by the Company
    Capitalization
` : data.valuationCap ? `
The Conversion Price shall be the price per share equal to the Valuation Cap
divided by the Company Capitalization
` : data.discountRate ? `
The Conversion Price shall be the Discount Price
` : ''}

1.2 LIQUIDITY EVENT

If there is a Liquidity Event before the termination of this SAFE, the
Investor will automatically be entitled to receive a portion of the proceeds
equal to the greater of:

(i)  the Purchase Amount, or
(ii) the amount payable on the number of shares of Common Stock equal to
     the Purchase Amount divided by the Liquidity Price

${data.valuationCap ? `
The Liquidity Price is the price per share equal to the Valuation Cap
divided by the Liquidity Capitalization.
` : ''}

1.3 DISSOLUTION EVENT

If there is a Dissolution Event before the termination of this SAFE, the
Investor will automatically be entitled to receive a portion of the proceeds
equal to the Purchase Amount, subject to the preferences and priorities of
other securities.

1.4 TERMINATION

This SAFE will automatically terminate upon the earliest to occur of:
(a) the issuance of shares pursuant to Section 1.1;
(b) the payment of amounts pursuant to Section 1.2;
(c) the payment of amounts pursuant to Section 1.3; or
(d) by mutual written agreement of the Company and the Investor.

================================================================================
2. DEFINITIONS
================================================================================

"COMPANY CAPITALIZATION" means the sum of:
(a) all shares of Capital Stock issued and outstanding, assuming full
    conversion of all convertible securities;
(b) all shares of Common Stock reserved for issuance under equity incentive
    plans; and
(c) all shares issuable upon conversion of SAFEs, calculated using the
    Valuation Cap.

"EQUITY FINANCING" means a bona fide transaction or series of transactions
with the principal purpose of raising capital, pursuant to which the Company
issues and sells Preferred Stock at a fixed valuation.

"LIQUIDITY EVENT" means a Change of Control or an IPO.

"SAFE PREFERRED STOCK" means the shares of Preferred Stock issued in the
Equity Financing with the identical rights, privileges, preferences, and
restrictions.

================================================================================
3. COMPANY REPRESENTATIONS
================================================================================

The Company represents and warrants that:

(a) The Company is duly organized, validly existing, and in good standing;
(b) The Company has the corporate power and authority to execute this SAFE;
(c) This SAFE constitutes a valid and legally binding obligation; and
(d) The issuance of shares pursuant to this SAFE will not violate any law
    or agreement.

================================================================================
4. INVESTOR REPRESENTATIONS
================================================================================

The Investor represents and warrants that:

(a) The Investor has legal authority to enter into this SAFE;
(b) The Investor is an "accredited investor" as defined by Rule 501;
(c) The Investor is acquiring this SAFE for investment purposes only;
(d) The Investor understands this SAFE and the securities are not registered;
(e) The Investor has had the opportunity to ask questions and receive answers.

================================================================================
5. MISCELLANEOUS
================================================================================

5.1 GOVERNING LAW
This SAFE shall be governed by the laws of the State of Delaware.

5.2 ENTIRE AGREEMENT
This SAFE constitutes the entire agreement between the parties.

5.3 NOTICES
All notices shall be in writing and shall be deemed given when delivered
personally, by email, or by certified mail.

5.4 AMENDMENTS
This SAFE may only be amended by a written instrument signed by both parties.

5.5 ASSIGNMENT
The Investor may not assign this SAFE without the Company's written consent.

================================================================================
SIGNATURES
================================================================================

COMPANY:
${data.companyName}

By:       _________________________________________
Name:
Title:
Date:


INVESTOR:
${data.investorName}

By:       _________________________________________
Name:
Title:
Date:

Address:  _________________________________________
          _________________________________________

Email:    _________________________________________

================================================================================
                    Generated by Alabobai Funding Department
================================================================================
`
  },

  // ============================================================================
  // INVESTOR UPDATE EMAIL
  // ============================================================================
  investorUpdate: {
    name: 'Investor Update',
    description: 'Monthly or quarterly investor update email',
    fields: ['companyName', 'period', 'highlights', 'metrics', 'asks'],
    generate: (data: {
      companyName: string;
      founderName: string;
      period: string;
      highlights: string[];
      lowlights?: string[];
      metrics: Array<{ name: string; value: string; change?: string }>;
      product: string[];
      team: string[];
      fundraising?: string;
      asks: string[];
      nextMilestones: string[];
    }) => `
================================================================================
${data.companyName.toUpperCase()} INVESTOR UPDATE
${data.period}
================================================================================

Hi Investors,

Hope this update finds you well! Here's what's been happening at ${data.companyName}.

================================================================================
TL;DR
================================================================================

${data.highlights.slice(0, 3).map((h, i) => `${i + 1}. ${h}`).join('\n')}

================================================================================
KEY METRICS
================================================================================

${data.metrics.map(m => `${m.name.padEnd(25)} ${m.value.padStart(15)} ${m.change ? `(${m.change})` : ''}`).join('\n')}

================================================================================
HIGHLIGHTS
================================================================================

${data.highlights.map((h, i) => `${i + 1}. ${h}`).join('\n\n')}

${data.lowlights && data.lowlights.length > 0 ? `
================================================================================
CHALLENGES / LOWLIGHTS
================================================================================

${data.lowlights.map((l, i) => `${i + 1}. ${l}`).join('\n\n')}
` : ''}

================================================================================
PRODUCT UPDATE
================================================================================

${data.product.map((p, i) => `- ${p}`).join('\n')}

================================================================================
TEAM UPDATE
================================================================================

${data.team.map((t, i) => `- ${t}`).join('\n')}

${data.fundraising ? `
================================================================================
FUNDRAISING
================================================================================

${data.fundraising}
` : ''}

================================================================================
ASKS - HOW YOU CAN HELP
================================================================================

${data.asks.map((a, i) => `${i + 1}. ${a}`).join('\n\n')}

================================================================================
NEXT MILESTONES
================================================================================

${data.nextMilestones.map((m, i) => `[ ] ${m}`).join('\n')}

================================================================================

Thank you for your continued support. Feel free to reply with any questions,
intros, or feedback.

Best,
${data.founderName}

================================================================================
                    Generated by Alabobai Funding Department
================================================================================
`
  }
};

export type FundingTemplateKey = keyof typeof FUNDING_TEMPLATES;

export function generateFundingDocument(templateKey: FundingTemplateKey, data: any): string {
  const template = FUNDING_TEMPLATES[templateKey];
  if (!template) {
    throw new Error(`Template not found: ${templateKey}`);
  }
  return template.generate(data);
}

export function listFundingTemplates() {
  return Object.entries(FUNDING_TEMPLATES).map(([key, value]) => ({
    key,
    name: value.name,
    description: value.description,
    fields: value.fields
  }));
}
