/**
 * Alabobai HR Department Templates
 * Job Descriptions, Offer Letters, Handbooks, HR Policies
 */

export const HR_TEMPLATES = {
  // ============================================================================
  // JOB DESCRIPTION
  // ============================================================================
  jobDescription: {
    name: 'Job Description',
    description: 'Comprehensive job posting template',
    fields: ['title', 'department', 'level', 'responsibilities', 'requirements', 'benefits'],
    generate: (data: {
      companyName: string;
      title: string;
      department: string;
      location: string;
      locationType: 'remote' | 'hybrid' | 'on-site';
      employmentType: 'full-time' | 'part-time' | 'contract' | 'internship';
      experienceLevel: 'entry' | 'mid' | 'senior' | 'lead' | 'executive';
      salaryRange?: { min: number; max: number };
      aboutCompany: string;
      aboutRole: string;
      responsibilities: string[];
      requirements: string[];
      niceToHave?: string[];
      benefits: string[];
      applicationProcess?: string;
    }) => `
================================================================================
${data.companyName.toUpperCase()}
JOB DESCRIPTION
================================================================================

POSITION: ${data.title}
DEPARTMENT: ${data.department}
LOCATION: ${data.location} (${data.locationType.toUpperCase()})
TYPE: ${data.employmentType.toUpperCase()}
LEVEL: ${data.experienceLevel.toUpperCase()}
${data.salaryRange ? `SALARY: $${data.salaryRange.min.toLocaleString()} - $${data.salaryRange.max.toLocaleString()} per year` : ''}

================================================================================
ABOUT ${data.companyName.toUpperCase()}
================================================================================

${data.aboutCompany}

================================================================================
ABOUT THE ROLE
================================================================================

${data.aboutRole}

================================================================================
RESPONSIBILITIES
================================================================================

What you'll do:

${data.responsibilities.map((r, i) => `${i + 1}. ${r}`).join('\n\n')}

================================================================================
REQUIREMENTS
================================================================================

What we're looking for:

${data.requirements.map((r, i) => `${i + 1}. ${r}`).join('\n\n')}

${data.niceToHave && data.niceToHave.length > 0 ? `
================================================================================
NICE TO HAVE
================================================================================

Bonus points if you have:

${data.niceToHave.map((n, i) => `- ${n}`).join('\n')}
` : ''}

================================================================================
BENEFITS & PERKS
================================================================================

What we offer:

${data.benefits.map((b, i) => `- ${b}`).join('\n')}

${data.applicationProcess ? `
================================================================================
HOW TO APPLY
================================================================================

${data.applicationProcess}
` : ''}

================================================================================
EQUAL OPPORTUNITY EMPLOYER
================================================================================

${data.companyName} is an equal opportunity employer. We celebrate diversity
and are committed to creating an inclusive environment for all employees.
We do not discriminate based on race, color, religion, sex, sexual
orientation, gender identity, national origin, age, disability, veteran
status, or any other protected characteristic.

================================================================================
                    Generated by Alabobai HR Department
================================================================================
`
  },

  // ============================================================================
  // OFFER LETTER
  // ============================================================================
  offerLetter: {
    name: 'Offer Letter',
    description: 'Employment offer letter template',
    fields: ['candidateName', 'position', 'salary', 'startDate', 'benefits'],
    generate: (data: {
      companyName: string;
      companyAddress: string;
      candidateName: string;
      candidateAddress?: string;
      position: string;
      department: string;
      reportsTo: string;
      employmentType: 'full-time' | 'part-time' | 'contract';
      startDate: string;
      salary: number;
      payFrequency: 'weekly' | 'bi-weekly' | 'semi-monthly' | 'monthly';
      bonus?: {
        type: string;
        amount: string;
        details: string;
      };
      equity?: {
        shares: number;
        vestingSchedule: string;
      };
      benefits: string[];
      offerExpiration: string;
      signatoryName: string;
      signatoryTitle: string;
    }) => `
================================================================================
${data.companyName.toUpperCase()}
OFFER OF EMPLOYMENT
================================================================================

${data.companyAddress}

Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

${data.candidateName}
${data.candidateAddress || '[Candidate Address]'}

Dear ${data.candidateName.split(' ')[0]},

We are pleased to offer you the position of ${data.position} at
${data.companyName}. We believe your skills and experience are an excellent
match for our team, and we are excited about the opportunity to work together.

================================================================================
POSITION DETAILS
================================================================================

Position:          ${data.position}
Department:        ${data.department}
Reports To:        ${data.reportsTo}
Employment Type:   ${data.employmentType.charAt(0).toUpperCase() + data.employmentType.slice(1)}
Start Date:        ${data.startDate}
Work Location:     [To be specified]

================================================================================
COMPENSATION
================================================================================

BASE SALARY
--------------------------------------------------------------------------------
Annual Salary:     $${data.salary.toLocaleString()} per year
Pay Frequency:     ${data.payFrequency.charAt(0).toUpperCase() + data.payFrequency.slice(1)}
Gross Per Period:  $${(data.salary / (data.payFrequency === 'weekly' ? 52 : data.payFrequency === 'bi-weekly' ? 26 : data.payFrequency === 'semi-monthly' ? 24 : 12)).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}

Your salary will be subject to applicable federal, state, and local tax
withholdings and other authorized deductions.

${data.bonus ? `
BONUS
--------------------------------------------------------------------------------
Bonus Type:        ${data.bonus.type}
Amount:            ${data.bonus.amount}
Details:           ${data.bonus.details}
` : ''}

${data.equity ? `
EQUITY COMPENSATION
--------------------------------------------------------------------------------
Stock Options:     ${data.equity.shares.toLocaleString()} shares
Vesting Schedule:  ${data.equity.vestingSchedule}

Equity grants are subject to the terms and conditions of ${data.companyName}'s
Equity Incentive Plan and your individual Stock Option Agreement.
` : ''}

================================================================================
BENEFITS
================================================================================

As a ${data.employmentType} employee, you will be eligible for the following
benefits:

${data.benefits.map((b, i) => `${i + 1}. ${b}`).join('\n')}

Specific details regarding benefits eligibility and enrollment will be
provided during your onboarding process.

================================================================================
TERMS OF EMPLOYMENT
================================================================================

1. EMPLOYMENT AT WILL
   Your employment with ${data.companyName} is "at will," meaning either you
   or the Company may terminate the employment relationship at any time, with
   or without cause or notice.

2. CONTINGENCIES
   This offer is contingent upon:
   - Successful completion of a background check
   - Verification of your eligibility to work in the United States
   - Execution of required employment documents

3. CONFIDENTIALITY
   As a condition of employment, you will be required to sign
   ${data.companyName}'s Confidentiality and Invention Assignment Agreement.

4. COMPANY POLICIES
   You will be expected to abide by all company policies and procedures,
   including those outlined in the Employee Handbook.

================================================================================
ACCEPTANCE
================================================================================

To accept this offer, please sign and date this letter and return it by
${data.offerExpiration}. If we do not receive your acceptance by this date,
this offer will be considered expired.

We are truly excited about the prospect of you joining our team. If you have
any questions about this offer, please don't hesitate to contact us.

Welcome to ${data.companyName}!

Sincerely,

_________________________________________
${data.signatoryName}
${data.signatoryTitle}
${data.companyName}

================================================================================
ACCEPTANCE OF OFFER
================================================================================

I, ${data.candidateName}, accept the offer of employment as described above.
I understand that this letter does not constitute a contract of employment
for any specific duration.

_________________________________________
Signature

_________________________________________
Date

================================================================================
                    Generated by Alabobai HR Department
================================================================================
`
  },

  // ============================================================================
  // EMPLOYEE HANDBOOK (OUTLINE)
  // ============================================================================
  employeeHandbook: {
    name: 'Employee Handbook',
    description: 'Company employee handbook template',
    fields: ['companyName', 'policies', 'benefits', 'culture'],
    generate: (data: {
      companyName: string;
      effectiveDate: string;
      mission: string;
      values: string[];
      ceoName: string;
      ceoMessage: string;
      policies: {
        workSchedule: string;
        remoteWork: string;
        timeOff: {
          vacation: string;
          sick: string;
          holidays: string[];
          parental: string;
        };
        codeOfConduct: string[];
        dressCode: string;
      };
      benefits: {
        health: string;
        retirement: string;
        professional: string;
        other: string[];
      };
    }) => `
================================================================================
${data.companyName.toUpperCase()}
EMPLOYEE HANDBOOK
================================================================================

Effective Date: ${data.effectiveDate}

CONFIDENTIAL - FOR INTERNAL USE ONLY

This handbook is intended to provide employees with information about
${data.companyName}'s policies, procedures, and benefits. It is not a
contract of employment.

================================================================================
TABLE OF CONTENTS
================================================================================

1.  Welcome & Introduction
2.  Our Mission & Values
3.  Employment Policies
4.  Work Schedule & Attendance
5.  Time Off & Leave
6.  Compensation & Benefits
7.  Professional Development
8.  Code of Conduct
9.  Workplace Safety
10. Technology & Security
11. Performance Management
12. Separation of Employment
13. Acknowledgment

================================================================================
1. WELCOME & INTRODUCTION
================================================================================

MESSAGE FROM THE CEO
--------------------------------------------------------------------------------

Dear Team Member,

${data.ceoMessage}

Welcome to ${data.companyName}!

Sincerely,
${data.ceoName}
Chief Executive Officer

ABOUT THIS HANDBOOK
--------------------------------------------------------------------------------

This Employee Handbook is designed to help you understand ${data.companyName}'s
expectations, policies, and the benefits available to you. Please read it
carefully and keep it accessible for future reference.

This handbook supersedes all previous handbooks and policy statements.
${data.companyName} reserves the right to modify, revoke, or add to any
policies at any time.

================================================================================
2. OUR MISSION & VALUES
================================================================================

OUR MISSION
--------------------------------------------------------------------------------

${data.mission}

OUR VALUES
--------------------------------------------------------------------------------

${data.values.map((v, i) => `${i + 1}. ${v}`).join('\n\n')}

================================================================================
3. EMPLOYMENT POLICIES
================================================================================

EMPLOYMENT AT WILL
--------------------------------------------------------------------------------

Employment with ${data.companyName} is "at will," meaning that either the
employee or the Company may terminate the employment relationship at any
time, with or without cause or prior notice.

EQUAL EMPLOYMENT OPPORTUNITY
--------------------------------------------------------------------------------

${data.companyName} is committed to providing equal employment opportunities
to all employees and applicants. We do not discriminate based on race, color,
religion, sex, sexual orientation, gender identity, national origin, age,
disability, veteran status, or any other protected characteristic.

ANTI-HARASSMENT
--------------------------------------------------------------------------------

${data.companyName} is committed to providing a work environment free from
harassment of any kind. Harassment based on any protected characteristic is
strictly prohibited and will not be tolerated.

================================================================================
4. WORK SCHEDULE & ATTENDANCE
================================================================================

WORK SCHEDULE
--------------------------------------------------------------------------------

${data.policies.workSchedule}

REMOTE WORK POLICY
--------------------------------------------------------------------------------

${data.policies.remoteWork}

ATTENDANCE
--------------------------------------------------------------------------------

Regular and reliable attendance is essential. Employees are expected to:
- Arrive on time for scheduled work hours
- Notify their manager as soon as possible in case of absence
- Follow established procedures for requesting time off

================================================================================
5. TIME OFF & LEAVE
================================================================================

VACATION / PAID TIME OFF (PTO)
--------------------------------------------------------------------------------

${data.policies.timeOff.vacation}

SICK LEAVE
--------------------------------------------------------------------------------

${data.policies.timeOff.sick}

COMPANY HOLIDAYS
--------------------------------------------------------------------------------

${data.companyName} observes the following holidays:

${data.policies.timeOff.holidays.map((h, i) => `${i + 1}. ${h}`).join('\n')}

PARENTAL LEAVE
--------------------------------------------------------------------------------

${data.policies.timeOff.parental}

OTHER LEAVE
--------------------------------------------------------------------------------

- Bereavement Leave: [Details]
- Jury Duty: [Details]
- Military Leave: [Details]
- Personal Leave: [Details]

================================================================================
6. COMPENSATION & BENEFITS
================================================================================

PAY PRACTICES
--------------------------------------------------------------------------------

- Pay periods: [Bi-weekly/Semi-monthly]
- Pay day: [Day of week]
- Direct deposit is [required/available]

HEALTH BENEFITS
--------------------------------------------------------------------------------

${data.benefits.health}

RETIREMENT BENEFITS
--------------------------------------------------------------------------------

${data.benefits.retirement}

ADDITIONAL BENEFITS
--------------------------------------------------------------------------------

${data.benefits.other.map((b, i) => `- ${b}`).join('\n')}

================================================================================
7. PROFESSIONAL DEVELOPMENT
================================================================================

${data.benefits.professional}

We encourage continuous learning and growth. Resources include:
- Training programs
- Conference attendance
- Online learning subscriptions
- Mentorship programs
- Tuition reimbursement (if applicable)

================================================================================
8. CODE OF CONDUCT
================================================================================

All employees are expected to conduct themselves in a professional manner
and adhere to the following standards:

${data.policies.codeOfConduct.map((c, i) => `${i + 1}. ${c}`).join('\n\n')}

DRESS CODE
--------------------------------------------------------------------------------

${data.policies.dressCode}

CONFLICT OF INTEREST
--------------------------------------------------------------------------------

Employees must avoid situations where personal interests could conflict with
the interests of ${data.companyName}. Any potential conflicts should be
disclosed to management.

================================================================================
9. WORKPLACE SAFETY
================================================================================

${data.companyName} is committed to maintaining a safe and healthy work
environment. All employees are expected to:

- Follow safety rules and procedures
- Report unsafe conditions or practices
- Report all work-related injuries immediately
- Participate in safety training

DRUG-FREE WORKPLACE
--------------------------------------------------------------------------------

${data.companyName} maintains a drug-free workplace. The use, sale, or
possession of illegal drugs or alcohol on company premises or during work
hours is strictly prohibited.

================================================================================
10. TECHNOLOGY & SECURITY
================================================================================

ACCEPTABLE USE
--------------------------------------------------------------------------------

Company technology resources (computers, email, internet, etc.) are provided
for business purposes. Employees should:

- Use resources responsibly and professionally
- Protect confidential information
- Not install unauthorized software
- Follow password and security protocols

CONFIDENTIALITY
--------------------------------------------------------------------------------

Employees may have access to confidential information. This information must
be protected and not disclosed to unauthorized parties.

================================================================================
11. PERFORMANCE MANAGEMENT
================================================================================

PERFORMANCE REVIEWS
--------------------------------------------------------------------------------

Performance reviews are conducted [annually/semi-annually/quarterly]. Reviews
are an opportunity to:

- Discuss accomplishments and areas for improvement
- Set goals for the upcoming period
- Discuss career development

PROGRESSIVE DISCIPLINE
--------------------------------------------------------------------------------

When necessary, ${data.companyName} may use progressive discipline, which
may include:

1. Verbal warning
2. Written warning
3. Final written warning
4. Termination

Serious misconduct may result in immediate termination.

================================================================================
12. SEPARATION OF EMPLOYMENT
================================================================================

VOLUNTARY RESIGNATION
--------------------------------------------------------------------------------

Employees who wish to resign should provide at least two weeks' written
notice to their manager.

INVOLUNTARY TERMINATION
--------------------------------------------------------------------------------

Termination decisions are made carefully and in accordance with company
policies and applicable laws.

EXIT PROCESS
--------------------------------------------------------------------------------

Upon separation, employees must:
- Return all company property
- Complete exit interview
- Submit final timesheets
- Transition work responsibilities

================================================================================
13. ACKNOWLEDGMENT
================================================================================

I acknowledge that I have received and read the ${data.companyName} Employee
Handbook. I understand that this handbook is not a contract of employment
and that my employment is at-will.

I agree to abide by the policies and procedures outlined in this handbook.
I understand that ${data.companyName} reserves the right to modify these
policies at any time.

Employee Name (Print): _______________________________________

Employee Signature: _______________________________________

Date: _______________________________________

================================================================================
                    Generated by Alabobai HR Department
================================================================================
`
  },

  // ============================================================================
  // PERFORMANCE REVIEW
  // ============================================================================
  performanceReview: {
    name: 'Performance Review',
    description: 'Employee performance evaluation template',
    fields: ['employeeName', 'reviewPeriod', 'ratings', 'goals'],
    generate: (data: {
      companyName: string;
      employeeName: string;
      employeeTitle: string;
      department: string;
      managerName: string;
      reviewPeriod: string;
      reviewDate: string;
      overallRating: 1 | 2 | 3 | 4 | 5;
      categories: Array<{
        name: string;
        rating: 1 | 2 | 3 | 4 | 5;
        comments: string;
      }>;
      accomplishments: string[];
      areasForImprovement: string[];
      goalsFromLastPeriod?: Array<{
        goal: string;
        status: 'exceeded' | 'met' | 'partially-met' | 'not-met';
        comments: string;
      }>;
      goalsForNextPeriod: string[];
      developmentPlan?: string[];
      employeeComments?: string;
    }) => {
      const ratingLabels: Record<number, string> = {
        1: 'Needs Improvement',
        2: 'Below Expectations',
        3: 'Meets Expectations',
        4: 'Exceeds Expectations',
        5: 'Outstanding'
      };

      return `
================================================================================
${data.companyName.toUpperCase()}
PERFORMANCE REVIEW
================================================================================

REVIEW PERIOD: ${data.reviewPeriod}
REVIEW DATE:   ${data.reviewDate}

================================================================================
EMPLOYEE INFORMATION
================================================================================

Employee Name:     ${data.employeeName}
Title:             ${data.employeeTitle}
Department:        ${data.department}
Manager:           ${data.managerName}

================================================================================
RATING SCALE
================================================================================

5 - Outstanding:           Consistently exceeds all expectations
4 - Exceeds Expectations:  Frequently exceeds expectations
3 - Meets Expectations:    Consistently meets expectations
2 - Below Expectations:    Sometimes meets expectations
1 - Needs Improvement:     Rarely meets expectations

================================================================================
OVERALL PERFORMANCE RATING
================================================================================

                    [ ${data.overallRating} - ${ratingLabels[data.overallRating]} ]

================================================================================
PERFORMANCE BY CATEGORY
================================================================================

${data.categories.map(cat => `
${cat.name.toUpperCase()}
Rating: ${cat.rating} - ${ratingLabels[cat.rating]}
--------------------------------------------------------------------------------
${cat.comments}
`).join('\n')}

================================================================================
KEY ACCOMPLISHMENTS
================================================================================

${data.accomplishments.map((a, i) => `${i + 1}. ${a}`).join('\n\n')}

================================================================================
AREAS FOR IMPROVEMENT
================================================================================

${data.areasForImprovement.map((a, i) => `${i + 1}. ${a}`).join('\n\n')}

${data.goalsFromLastPeriod && data.goalsFromLastPeriod.length > 0 ? `
================================================================================
REVIEW OF PREVIOUS GOALS
================================================================================

${data.goalsFromLastPeriod.map((g, i) => `
Goal ${i + 1}: ${g.goal}
Status: ${g.status.toUpperCase().replace('-', ' ')}
Comments: ${g.comments}
`).join('\n')}
` : ''}

================================================================================
GOALS FOR NEXT REVIEW PERIOD
================================================================================

${data.goalsForNextPeriod.map((g, i) => `
Goal ${i + 1}: ${g}
Target Date: _______________
Measurement: _______________
`).join('\n')}

${data.developmentPlan && data.developmentPlan.length > 0 ? `
================================================================================
DEVELOPMENT PLAN
================================================================================

${data.developmentPlan.map((d, i) => `${i + 1}. ${d}`).join('\n\n')}
` : ''}

================================================================================
EMPLOYEE COMMENTS
================================================================================

${data.employeeComments || '[Employee may add comments here]'}

________________________________________________________________________________
________________________________________________________________________________
________________________________________________________________________________

================================================================================
SIGNATURES
================================================================================

By signing below, I acknowledge that I have reviewed and discussed this
performance evaluation with my manager. My signature does not necessarily
indicate agreement with the evaluation.

EMPLOYEE:

_________________________________________    Date: ______________
${data.employeeName}


MANAGER:

_________________________________________    Date: ______________
${data.managerName}


HR REPRESENTATIVE:

_________________________________________    Date: ______________
Name: ___________________________

================================================================================
                    Generated by Alabobai HR Department
================================================================================
`;
    }
  },

  // ============================================================================
  // ONBOARDING CHECKLIST
  // ============================================================================
  onboardingChecklist: {
    name: 'Onboarding Checklist',
    description: 'New employee onboarding checklist',
    fields: ['employeeName', 'startDate', 'tasks'],
    generate: (data: {
      companyName: string;
      employeeName: string;
      position: string;
      department: string;
      manager: string;
      buddy?: string;
      startDate: string;
      itContact: string;
      hrContact: string;
    }) => `
================================================================================
${data.companyName.toUpperCase()}
NEW EMPLOYEE ONBOARDING CHECKLIST
================================================================================

EMPLOYEE: ${data.employeeName}
POSITION: ${data.position}
DEPARTMENT: ${data.department}
MANAGER: ${data.manager}
${data.buddy ? `BUDDY: ${data.buddy}` : ''}
START DATE: ${data.startDate}

IT Contact: ${data.itContact}
HR Contact: ${data.hrContact}

================================================================================
PRE-FIRST DAY (HR & MANAGER)
================================================================================

[ ] Offer letter signed and returned
[ ] Background check completed
[ ] I-9 documentation collected
[ ] Workstation/equipment ordered
[ ] Email account created
[ ] System access provisioned
[ ] Welcome email sent to team
[ ] First day schedule created
[ ] Buddy assigned
[ ] Training schedule planned

================================================================================
DAY 1 - WELCOME & ORIENTATION
================================================================================

MORNING
--------------------------------------------------------------------------------
[ ] Welcome meeting with manager
[ ] Office tour / virtual workspace introduction
[ ] Meet the team introductions
[ ] IT setup and equipment
    [ ] Computer/laptop
    [ ] Email access
    [ ] Communication tools (Slack, Teams, etc.)
    [ ] Calendar setup
[ ] Building access / security badge
[ ] Parking information (if applicable)

AFTERNOON
--------------------------------------------------------------------------------
[ ] HR orientation
    [ ] Review employee handbook
    [ ] Company policies overview
    [ ] Benefits enrollment
    [ ] Emergency procedures
[ ] Complete required paperwork
    [ ] W-4 tax form
    [ ] Direct deposit form
    [ ] Emergency contact form
    [ ] Confidentiality agreement
[ ] First lunch with team/buddy

================================================================================
WEEK 1 - FOUNDATION
================================================================================

[ ] Complete all required training
    [ ] Security awareness training
    [ ] Harassment prevention training
    [ ] Company systems training
    [ ] Role-specific training
[ ] Review team goals and projects
[ ] Meet with key stakeholders
[ ] Understand team workflows
[ ] Access to necessary tools and platforms
    [ ] _______________
    [ ] _______________
    [ ] _______________
[ ] Daily check-ins with manager
[ ] End-of-week review with manager

================================================================================
WEEKS 2-4 - INTEGRATION
================================================================================

WEEK 2
--------------------------------------------------------------------------------
[ ] Begin working on assigned tasks/projects
[ ] Continue stakeholder introductions
[ ] Participate in team meetings
[ ] Review department processes
[ ] Check-in with buddy
[ ] Weekly 1:1 with manager

WEEK 3
--------------------------------------------------------------------------------
[ ] Take on more responsibilities
[ ] Complete remaining training modules
[ ] Join cross-functional meetings
[ ] Weekly 1:1 with manager

WEEK 4
--------------------------------------------------------------------------------
[ ] First month review with manager
[ ] Feedback collection
[ ] Goal setting for next 60 days
[ ] Address any questions or concerns

================================================================================
30-60-90 DAY MILESTONES
================================================================================

30 DAYS
--------------------------------------------------------------------------------
[ ] Completed all onboarding training
[ ] Understands role and responsibilities
[ ] Integrated into team workflows
[ ] Met with all key stakeholders
[ ] First project/task completed
[ ] Feedback meeting with manager

60 DAYS
--------------------------------------------------------------------------------
[ ] Contributing independently
[ ] Understands company culture and values
[ ] Building cross-functional relationships
[ ] Progress toward initial goals
[ ] Feedback meeting with manager

90 DAYS
--------------------------------------------------------------------------------
[ ] Fully productive in role
[ ] Performance review
[ ] Goal review and setting
[ ] Probationary period complete (if applicable)
[ ] Onboarding survey completed

================================================================================
SYSTEMS ACCESS CHECKLIST
================================================================================

| System | Requested | Granted | Notes |
|--------|-----------|---------|-------|
| Email | [ ] | [ ] | |
| Slack/Teams | [ ] | [ ] | |
| HRIS | [ ] | [ ] | |
| Project Mgmt | [ ] | [ ] | |
| CRM | [ ] | [ ] | |
| Code Repo | [ ] | [ ] | |
| VPN | [ ] | [ ] | |
| _________ | [ ] | [ ] | |
| _________ | [ ] | [ ] | |

================================================================================
KEY CONTACTS
================================================================================

Manager:        ${data.manager}
Buddy:          ${data.buddy || 'N/A'}
HR:             ${data.hrContact}
IT:             ${data.itContact}
Payroll:        _______________
Facilities:     _______________

================================================================================
NOTES
================================================================================

________________________________________________________________________________
________________________________________________________________________________
________________________________________________________________________________
________________________________________________________________________________

================================================================================
ONBOARDING COMPLETION
================================================================================

Employee Signature: _________________________ Date: ____________

Manager Signature: _________________________ Date: ____________

HR Signature: _________________________ Date: ____________

================================================================================
                    Generated by Alabobai HR Department
================================================================================
`
  },

  // ============================================================================
  // TERMINATION LETTER
  // ============================================================================
  terminationLetter: {
    name: 'Termination Letter',
    description: 'Employment termination notification',
    fields: ['employeeName', 'terminationDate', 'reason', 'finalPay'],
    generate: (data: {
      companyName: string;
      companyAddress: string;
      employeeName: string;
      employeeAddress?: string;
      position: string;
      department: string;
      terminationDate: string;
      lastWorkingDay: string;
      terminationType: 'voluntary' | 'involuntary' | 'layoff' | 'end-of-contract';
      reason: string;
      finalPayDate: string;
      severanceDetails?: string;
      benefitsContinuation: string;
      returnItems: string[];
      hrContact: string;
      signatoryName: string;
      signatoryTitle: string;
    }) => `
================================================================================
${data.companyName.toUpperCase()}
SEPARATION NOTICE
================================================================================

${data.companyAddress}

Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

CONFIDENTIAL

${data.employeeName}
${data.employeeAddress || '[Employee Address]'}

Re: Separation of Employment

Dear ${data.employeeName.split(' ')[0]},

${data.terminationType === 'voluntary'
  ? `This letter confirms your resignation from your position as ${data.position} in the ${data.department} department at ${data.companyName}.`
  : data.terminationType === 'layoff'
  ? `It is with regret that we inform you that your position as ${data.position} in the ${data.department} department has been eliminated due to organizational restructuring.`
  : data.terminationType === 'end-of-contract'
  ? `This letter confirms that your contract as ${data.position} in the ${data.department} department will conclude as scheduled.`
  : `This letter confirms the termination of your employment as ${data.position} in the ${data.department} department at ${data.companyName}.`
}

================================================================================
SEPARATION DETAILS
================================================================================

Position:             ${data.position}
Department:           ${data.department}
Last Working Day:     ${data.lastWorkingDay}
Effective Date:       ${data.terminationDate}
Reason:               ${data.reason}

================================================================================
FINAL PAY
================================================================================

Your final paycheck will be issued on ${data.finalPayDate} and will include:

- All earned wages through your last working day
- Accrued but unused paid time off (PTO), if applicable
- Any expense reimbursements owed

${data.severanceDetails ? `
SEVERANCE
--------------------------------------------------------------------------------
${data.severanceDetails}
` : ''}

================================================================================
BENEFITS
================================================================================

${data.benefitsContinuation}

Health Insurance (COBRA):
You will receive separate notification regarding your rights to continue
health insurance coverage under COBRA. This notice will be sent within
14 days of your termination date.

Retirement Plans:
Information regarding your 401(k) or other retirement plan options will
be provided separately.

================================================================================
COMPANY PROPERTY
================================================================================

Please return the following items by your last working day:

${data.returnItems.map((item, i) => `[ ] ${item}`).join('\n')}

================================================================================
CONFIDENTIALITY REMINDER
================================================================================

Please be reminded that your obligations under the Confidentiality and
Invention Assignment Agreement you signed remain in effect. You must
continue to maintain the confidentiality of all proprietary information.

================================================================================
REFERENCES
================================================================================

All reference requests should be directed to Human Resources. We will
confirm dates of employment and position held only.

================================================================================
EXIT PROCESS
================================================================================

Please complete the following before your departure:

[ ] Return all company property (listed above)
[ ] Complete exit interview with HR
[ ] Update address for tax documents (W-2)
[ ] Transition all work and documentation

If you have any questions about this separation or the exit process,
please contact ${data.hrContact}.

================================================================================

We wish you the best in your future endeavors.

Sincerely,

_________________________________________
${data.signatoryName}
${data.signatoryTitle}
${data.companyName}

================================================================================
ACKNOWLEDGMENT
================================================================================

I acknowledge receipt of this separation notice.

_________________________________________    Date: ______________
${data.employeeName}

================================================================================
                    Generated by Alabobai HR Department
================================================================================
`
  }
};

export type HRTemplateKey = keyof typeof HR_TEMPLATES;

export function generateHRDocument(templateKey: HRTemplateKey, data: any): string {
  const template = HR_TEMPLATES[templateKey];
  if (!template) {
    throw new Error(`Template not found: ${templateKey}`);
  }
  return template.generate(data);
}

export function listHRTemplates() {
  return Object.entries(HR_TEMPLATES).map(([key, value]) => ({
    key,
    name: value.name,
    description: value.description,
    fields: value.fields
  }));
}
